#! /bin/bash

# Details to deploy client to github pages
source .env.local

echo -e """ \033[32m
===========================
DEPLOYING BUNDLES TO GITHUB
BASE_HREF : \033[36m${GITHUB_REPO_NAME} \033[32m
=========================== \033[0m
"""

# Build pages for github deployment
NEXT_PUBLIC_BASE_HREF="/$GITHUB_REPO_NAME" ./_client_manager build

# Build some node code
read -r -d '' NODECMD <<EOM
  const ghpages = require("gh-pages");
  ghpages.publish("out", {dotfiles: true}, function (err) {
    if (!!err) {
      console.log("OH NO! STH WENT WRONG :(", err);
      process.exit(1);
    }
    console.log("DEPLOYED TO: https://${GITHUB_USER_NAME}.github.io/${GITHUB_REPO_NAME}/");
  })
EOM

# Execute node code
node -e "$NODECMD"
